# Forgejo Actions CI Workflow
# Runs on every push and pull request to build and test the project

name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: "10.0.x"
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    name: Build and Test
    runs-on: docker
    container:
      image: mcr.microsoft.com/dotnet/sdk:10.0
    steps:
      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Run tests
        run: dotnet test --no-build -c Release --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

  lint:
    name: Code Format Check
    runs-on: docker
    container:
      image: mcr.microsoft.com/dotnet/sdk:10.0
    steps:
      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Check formatting
        run: dotnet format --verify-no-changes --verbosity normal
        continue-on-error: true
