# Forgejo Actions Docker Workflow
# Builds and pushes Docker images on push to main and tags

name: Docker

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: docker
    steps:
      - name: Install git
        run: |
          which git || (apt-get update && apt-get install -y git) || (apk add --no-cache git) || true

      - name: Checkout code
        env:
          FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
        run: |
          if echo "${{ forgejo.ref }}" | grep -q "^refs/tags/"; then
            git clone --depth 1 \
              https://oauth2:${FORGEJO_TOKEN}@forge.csa.ba/${{ forgejo.repository }}.git .
            git fetch --tags
            git checkout ${{ forgejo.ref_name }}
          else
            git clone --depth 1 --branch ${{ forgejo.ref_name }} \
              https://oauth2:${FORGEJO_TOKEN}@forge.csa.ba/${{ forgejo.repository }}.git .
          fi

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use --name builder || true
          docker buildx inspect --bootstrap

      - name: Determine image tags
        id: tags
        run: |
          TAGS=""
          REF="${{ forgejo.ref }}"
          REF_NAME="${{ forgejo.ref_name }}"
          REGISTRY="forge.csa.ba"
          IMAGE="${{ forgejo.repository }}"

          if echo "$REF" | grep -q "^refs/tags/"; then
            # Tag push - use version tag and latest
            VERSION="$REF_NAME"
            TAGS="${REGISTRY}/${IMAGE}:latest,${REGISTRY}/${IMAGE}:${VERSION}"
          elif echo "$REF" | grep -q "^refs/heads/main$"; then
            # Main branch push
            TAGS="${REGISTRY}/${IMAGE}:main-latest"
          else
            # Other branches - use commit SHA
            TAGS="${REGISTRY}/${IMAGE}:${{ forgejo.sha }}"
          fi

          echo "tags=${TAGS}" >> $FORGEJO_OUTPUT
          echo "Image tags: ${TAGS}"

      - name: Login to Forgejo Container Registry
        env:
          FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
        run: |
          echo "${FORGEJO_TOKEN}" | docker login forge.csa.ba -u ${{ forgejo.repository_owner }} --password-stdin

      - name: Build and push Docker image
        run: |
          TAGS="${{ steps.tags.outputs.tags }}"

          # Convert comma-separated tags to -t arguments
          TAG_ARGS=""
          for tag in $(echo "$TAGS" | tr ',' ' '); do
            TAG_ARGS="$TAG_ARGS -t $tag"
          done

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            $TAG_ARGS \
            --label "org.opencontainers.image.source=${{ forgejo.server_url }}/${{ forgejo.repository }}" \
            --label "org.opencontainers.image.revision=${{ forgejo.sha }}" \
            --label "org.opencontainers.image.created=$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
            .

      - name: Logout from Container Registry
        if: always()
        run: docker logout forge.csa.ba
