# Forgejo Actions Release Workflow
# Triggered on version tags to build release binaries

name: Release

on:
  push:
    tags:
      - "v*"

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-and-release:
    name: Build and Release
    runs-on: docker
    container:
      image: mcr.microsoft.com/dotnet/sdk:10.0
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git curl jq

      - name: Checkout code
        env:
          FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
        run: |
          git clone --depth 1 \
            https://oauth2:${FORGEJO_TOKEN}@forge.csa.ba/${{ forgejo.repository }}.git .
          git fetch --tags
          git checkout ${{ forgejo.ref_name }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Run tests
        run: dotnet test --no-build -c Release --verbosity normal

      - name: Build linux-x64 binary
        run: |
          dotnet publish src/Csharparr/Csharparr.csproj \
            -c Release \
            -r linux-x64 \
            --self-contained true \
            -p:PublishSingleFile=true \
            -p:PublishTrimmed=false \
            -p:IncludeNativeLibrariesForSelfExtract=true \
            -p:EnableCompressionInSingleFile=true \
            -o ./publish/linux-x64

      - name: Build linux-arm64 binary
        run: |
          dotnet publish src/Csharparr/Csharparr.csproj \
            -c Release \
            -r linux-arm64 \
            --self-contained true \
            -p:PublishSingleFile=true \
            -p:PublishTrimmed=false \
            -p:IncludeNativeLibrariesForSelfExtract=true \
            -p:EnableCompressionInSingleFile=true \
            -o ./publish/linux-arm64

      - name: Prepare release artifacts
        run: |
          mkdir -p ./release
          mv ./publish/linux-x64/csharparr ./release/csharparr-linux-x64
          mv ./publish/linux-arm64/csharparr ./release/csharparr-linux-arm64
          cd release
          sha256sum csharparr-linux-x64 > csharparr-linux-x64.sha256
          sha256sum csharparr-linux-arm64 > csharparr-linux-arm64.sha256
          ls -la

      - name: Create release and upload assets
        env:
          FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
        run: |
          TAG_NAME="${{ forgejo.ref_name }}"
          REPO="${{ forgejo.repository }}"
          API_URL="${{ forgejo.api_url }}"

          echo "Creating release for tag: $TAG_NAME"

          # Check if release already exists
          EXISTING_RELEASE=$(curl -s \
            -H "Authorization: token ${FORGEJO_TOKEN}" \
            "${API_URL}/repos/${REPO}/releases/tags/${TAG_NAME}")

          RELEASE_ID=$(echo "$EXISTING_RELEASE" | jq -r '.id // empty')

          if [ -z "$RELEASE_ID" ] || [ "$RELEASE_ID" = "null" ]; then
            # Create new release
            RELEASE_RESPONSE=$(curl -s -X POST \
              -H "Authorization: token ${FORGEJO_TOKEN}" \
              -H "Content-Type: application/json" \
              "${API_URL}/repos/${REPO}/releases" \
              -d "{\"tag_name\": \"${TAG_NAME}\", \"name\": \"Release ${TAG_NAME}\", \"body\": \"Release ${TAG_NAME}\n\n## Downloads\n\n- csharparr-linux-x64: Linux x86_64 binary\n- csharparr-linux-arm64: Linux ARM64 binary\n\nSHA256 checksums are provided for verification.\", \"draft\": false, \"prerelease\": false}")

            RELEASE_ID=$(echo "$RELEASE_RESPONSE" | jq -r '.id')
            echo "Created new release with ID: $RELEASE_ID"
          else
            echo "Using existing release with ID: $RELEASE_ID"
          fi

          if [ -z "$RELEASE_ID" ] || [ "$RELEASE_ID" = "null" ]; then
            echo "Failed to get release ID"
            exit 1
          fi

          # Upload assets
          for file in ./release/*; do
            if [ -f "$file" ]; then
              FILENAME=$(basename "$file")
              echo "Uploading: $FILENAME"

              UPLOAD_RESPONSE=$(curl -s -X POST \
                -H "Authorization: token ${FORGEJO_TOKEN}" \
                -H "Content-Type: application/octet-stream" \
                "${API_URL}/repos/${REPO}/releases/${RELEASE_ID}/assets?name=${FILENAME}" \
                --data-binary "@${file}")

              echo "Upload response for $FILENAME: $(echo "$UPLOAD_RESPONSE" | jq -r '.name // .message // "unknown"')"
            fi
          done

          echo "Release completed successfully!"
